Add Release Policy document
solidusio/solidus.io pull request #541
Opened 2022-10-06 12:01 UTC by waiting-for-dev

Added the document about the intended release cadence for Solidus. We
cross-link it with the security page, as they're related.

We're also adding links to both the Security & Release Policy pages to the top
navigation.

We've taken the occasion to setup a docker-compose development environment, and
fix/update links on the README.

[solidusiopr.webm](https://user-images.githubusercontent.com/52650/194307262-df8d13ed-a531-4db9-ad22-ffe1c69140b2.webm)

2022-10-06 12:10 UTC, kennyadsl commented
OT: I'm taking a look at the build error, which is unrelated.

2022-10-06 12:12 UTC, mfrecchiami commented
I agree with @kennyadsl, we can add the two links under _Extensions_

<img width="496" alt="Screenshot 2022-10-06 at 14 09 16" src="https://user-images.githubusercontent.com/46188345/194309356-341530ec-cea0-4376-8e93-2421b8614587.png">

Does it make sense for you, @waiting-for-dev?

2022-10-06 15:12 UTC, waiting-for-dev commented
> I agree with @kennyadsl, we can add the two links under Extensions

Makes sense. Updated!

![Uploading screenshot-localhost_4567-2022.10.06-17_10_59.png…]()

2022-10-11 16:10 UTC, elia approved these changes
Left a couple of minor/optional suggestions

2022-10-17 05:23 UTC, waiting-for-dev commented on source/release_policy.html.erb
> +        issues and sensible bugs to be backported.
Makes sense. Done.

2022-10-17 05:23 UTC, waiting-for-dev commented on source/release_policy.html.erb
> +      <h2>Major versions: biennial releases</h2>
Fair enough. Done.

2022-10-17 14:09 UTC, waiting-for-dev commented
@kennyadsl , :green_circle: !

2022-10-17 15:14 UTC, adammathys approved these changes

2022-10-17 15:23 UTC, jarednorman requested changes

2022-10-18 05:04 UTC, waiting-for-dev commented on source/release_policy.html.erb
> +        <strong>every two years</strong>.
Thanks for the suggestion. Done!!

2022-10-18 16:47 UTC, jarednorman approved these changes

2022-10-19 03:05 UTC, merged